[Feature] Added Search with Categories and Sorting
jweiland-net/socialservices pull request #3
Opened 2019-04-16 09:29 UTC by Crontis

Added Search based on ext clubdirectory

2019-04-16 10:33 UTC, froemken requested changes

2019-04-16 10:33 UTC, froemken commented on Classes/Configuration/ExtConf.php
> + * @license http://www.gnu.org/licenses/gpl.html GNU General Public License, version 3 or later
Die Lizenz steht ja schon oben. Würde ich rausschmeißen.

2019-04-16 10:33 UTC, froemken commented on Classes/Controller/HelpdeskController.php
> +     * @return void
Return void wollten wir doch nicht mehr haben.

2019-04-16 10:33 UTC, froemken commented on Classes/Controller/HelpdeskController.php
>       * @return void
und wech mit void

2019-04-16 10:33 UTC, froemken commented on Classes/Domain/Model/Search.php
> +     * @return void
Raus mit diesen ganzen Leerzeilen in den Annotations und wech mit dem void.

2019-04-16 11:27 UTC, froemken requested changes

2019-04-16 11:27 UTC, froemken commented on Classes/Configuration/ExtConf.php
> +    public function getRootCategory(): int
Du nutzt strict types ohne strict_type Deklaration

2019-04-16 11:32 UTC, Crontis commented on Classes/Configuration/ExtConf.php
> +    public function getRootCategory(): int
Die Klasse hat eine strict types deklaration. Aber mhm.. Das Problem ist eher, dass die halbe Extension schon strict types ohne die deklaration nutzt.

2019-04-16 12:02 UTC, froemken commented on Classes/Configuration/ExtConf.php
> +    public function getRootCategory(): int
Lass uns die strict_types Deklaration nur da einbauen, wo Du auch Änderungen eingebaut hast.

2019-04-18 07:59 UTC, froemken approved these changes

2019-04-18 08:04 UTC, merged